version: '2'
services:

 elasticsearch-master:
  image: danielguerra/alpine-elasticsearch
  restart: always
  command: -Des.network.bind_host=elasticsearch-master --cluster.name=graylog --node.name=elasticsearch-master --discovery.zen.ping.multicast.enabled=false --network.host=elasticsearch-master
  hostname: elasticsearch-master
  volumes:
   - elastic-data:/usr/share/elasticsearch/data
  ports:
   - "9200:9200"
   - "9300:9300"

 elasticsearch-node01:
  image: danielguerra/alpine-elasticsearch
  restart: always
  command: -Des.network.bind_host=elasticsearch-node01 --cluster.name=graylog --node.name=elasticsearch-node01 --discovery.zen.ping.unicast.hosts=master:9300  --network.host=elasticsearch-node01
  hostname: elasticsearch-node01
  links:
   - "elasticsearch-master:master"
  volumes:
    - elastic-data:/usr/share/elasticsearch/data

 kibana:
  image: kibana
  restart: always
  hostname: kibana
  ports:
   - "5601:5601"
  links:
   - "elasticsearch-master:elasticsearch"

 mongodb:
  image: mongo:3
  restart: always
  command: "mongod --smallfiles"
  ports:
   - "27017:27017"
  volumes:
   - mongodb-conf:/etc/mongod.conf:ro
   - mongodb-data:/data/db

 graylog:
  image: "graylog2/server"
  restart: always
  volumes:
   - graylog-data:/usr/share/graylog/data/journal
   - graylog-conf:/usr/share/graylog/data/config
  environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
  ports:
   - "9000:9000"
   - "12201:12201"
   - "12201:12201/udp"
  links:
   - mongodb:mongo
   - elasticsearch-master:elasticsearch
   - rabbitmq:rabbitmq
  depends_on:
   - mongodb
   - rabbitmq
   - elasticsearch-master
   - elasticsearch-node01

 rabbitmq:
  image: rabbitmq:management
  restart: always
  hostname: rabbitmq
  ports:
   - 15672:15672
  environment:
    RABBITMQ_NODENAME: rabbitmq@rabbitmq
  volumes:
   - rabbitmq-data:/var/lib/rabbitmq/mnesia

 fluentd:
  image: fluent/fluentd
  build: docker-fluentd-amqp-graylog2
  restart: always
  links:
   - graylog:graylog
   - rabbitmq:rabbitmq
  volumes:
   - fluentd-logs:/fluentd/log
   - ./docker-fluentd-amqp-graylog2/fluent.conf:/fluentd/etc/fluent.conf
  environment:
   - FLUENTD_CONF=fluent.conf
  ports:
   - "24224:24224"
   - "5140:5140"

volumes:
 mongodb-data:
 mongodb-conf:
 graylog-data:
 graylog-conf:
 elastic-data: 
 fluentd-logs:
 rabbitmq-data:
